### ISSUE TITLE
Peer Circus

### ISSUE THREAD

**Issue by ursoft** [ursoft/zwift-offline#2] opened 2022-02-16 21:22 UTC
https://youtu.be/rnK2X4Bmnco?t=17
One profile continuously "moving" left and right, other - not. No steering module paired in both...

**Comment by ursoft** [comment] 2022-02-17 00:21
Tried online_update_freq=5 (instead of 1) - this change did not help me to reproduce bug in previous video. I've got blinks only. https://youtu.be/ssO-arffWdo?t=34

**Comment by oldnapalm** [comment] 2022-02-17 00:43
One update every 5 seconds is too few, the player will disappear after ~4 seconds (that's why we used one update every 3 seconds for ghosts). For pace partners, one update every 3 seconds made them behave strangely, then we used one update per second. For online players we used to send every update, but the problem was (I think) sometimes the server sent the same state twice (in case the remote player didn't update their state while the local player updated twice), then the workaround was to update once per second. Probably the correct approach would be having a control not to send the same state from a player twice to the same other player.

**Comment by oldnapalm** [comment] 2022-02-17 02:19
Try just removing `and t >= last_updates[player_id] + online_update_freq` from this line https://github.com/ursoft/zwift-offline/blob/master/standalone.py#L530

We already control the frequency here https://github.com/ursoft/zwift-offline/blob/master/standalone.py#L603

In your first video looks like you are receiving a delayed state, that's why the player makes the turns, because they are more advanced than the received state.

**Comment by ursoft** [comment] 2022-02-17 02:43
Hard to reproduce this issue today - maybe new algo (written as you suggested) will work better? [4affea6](https://github.com/ursoft/zwift-offline/commit/4affea6b9cc88d8a2cf2c44c8ab50fba9fd761ce)

**Comment by oldnapalm** [comment] 2022-02-17 11:14
Yes, it looks way better.

Do you think this was also the cause of #1?

**Comment by ursoft** [comment] 2022-02-17 15:33
> Do you think this was also the cause of #1?

I hope :-)

**Comment by oldnapalm** [comment] 2022-02-21 13:12
This video shows what I think is the cause of the wobbling issue... the client receives an update saying the remote player is in a given position going at a given speed and renders it, 3 seconds later it receives another update saying the position is behind where it was expected to be if the speed from the last update was kept, but actually the player slowed down a lot due to the sudden slope increase, then the client makes it go in circle to sync the position https://drive.google.com/file/d/1G0PrmuSHD-86AIfqfQzTKgg92icpsdy1/view?usp=sharing

**Comment by ursoft** [comment] 2022-02-21 23:05
Looks like my case. But I never seen full circle.

**Comment by oldnapalm** [comment] 2022-02-21 23:15
Yes, full circle occurs in more extreme conditions, when the position is too far from the predicted (in the video the speed was reduced very fast because of the slope, plus the bot is updated only each 3 seconds).

Was your case fully fixed with https://github.com/ursoft/zwift-offline/commit/4affea6b9cc88d8a2cf2c44c8ab50fba9fd761ce ?

BTW, tried your last commits but got errors due to missing changes (profile_pb2.Profile() -> profile_pb2.PlayerProfile(), etc.), assumed it's WIP.

**Comment by ursoft** [comment] 2022-02-21 23:24
> Was your case fully fixed with [4affea6](https://github.com/ursoft/zwift-offline/commit/4affea6b9cc88d8a2cf2c44c8ab50fba9fd761ce) ?

Need testing. Will take 1-2 weeks.

> BTW, tried your last commits but got errors due to missing changes (profile_pb2.Profile() -> profile_pb2.PlayerProfile(), etc.), assumed it's WIP.

Thanx, just added missed changes - please recheck

**Comment by oldnapalm** [comment] 2022-02-22 00:02
> Thanx, just added missed changes - please recheck

All good now, merged into zca branch, thanks.

**Comment by ursoft** [comment] 2022-02-22 00:11
> > Thanx, just added missed changes - please recheck
> 
> All good now, merged into zca branch, thanks.

need a way for private messaging for some themes (should be hidden from Zw devs)

**Comment by oldnapalm** [comment] 2022-02-22 00:39
Do you use discord? We have a private developers channel on https://discord.gg/GMdn8F8

**Comment by ursoft** [comment] 2022-02-22 01:21
> Do you use discord? We have a private developers channel on https://discord.gg/GMdn8F8

Tried ~6 month ago and now. Account locked immediately after first message.

**Comment by oldnapalm** [comment] 2022-02-22 01:28
Odd. Did you install the desktop or mobile app, or just joined using browser?

**Comment by ursoft** [comment] 2022-02-22 01:35
> Odd. Did you install the desktop or mobile app, or just joined using browser?

First time it was browser app, second - mobile app

**Comment by oldnapalm** [comment] 2022-02-22 01:40
I asked the server owner to check, I think he's sleeping now, probably will reply in a few hours.

**Comment by ursoft** [comment] 2022-02-22 01:47
> 

Just got automatic email "we banned you" - I'm a spamer )

**Comment by oldnapalm** [comment] 2022-02-22 01:54
Looks like a global discord issue, not specific of our server. On our server your profile looks normal, there are no banned accounts.

Try joining this one https://discord.gg/kw4dAUQUx4

**Comment by ursoft** [comment] 2022-02-22 02:11
> Looks like a global discord issue, not specific of our server. On our server your profile looks normal, there are no banned accounts.
> 
> Try joining this one https://discord.gg/kw4dAUQUx4

**Comment by ursoft** [comment] 2022-02-22 02:12
will close after all tests

**Comment by ursoft** [comment] 2022-02-28 05:10
https://youtu.be/f3lHoNLl6Gc - almost OK
This is Win10 virtual machine @year2014 server (not very fast) + zoffline (on the same Win10 environment).
On faster Notebook (year 2020, ZenBook Duo Pro) - no issues (not sure if it had problems before last fix).

**Comment by oldnapalm** [comment] 2022-02-28 12:06
Much better but still has a small glitch. I was thinking, the retail server sends updates from the 100 closest riders, so it probably doesn't send all updates from every rider. Maybe, before sending an update from a rider, we should not only check if it was already sent, but also check if the world_time is at least X ms (let's say 500 ms) newer than the last update sent?

**Comment by ursoft** [comment] 2022-02-28 13:16
Good suggestion. Also I missed that packets in UDP are not ordered, at least packets that are out of order should be discarded.

**Comment by oldnapalm** [comment] 2022-02-28 14:22
True.

Wouldn't `if for_news[peer_player_state.id] + 500 > peer_player_state.worldTime:` take care of packets order too?

https://github.com/ursoft/zwift-offline/blob/3e225bf9b4f317d86e4a2150495753da5cb87cb8/standalone.py#L507

**Comment by ursoft** [comment] 2022-02-28 14:38
> take care of packets order too?

Yes

```
        if for_news[peer_player_state.id] > peer_player_state.worldTime:
            print("is_state_new_for: out of order")
            return False #filter out
        #if peer_player_state.worldTime - for_news[peer_player_state.id] < 500:
        #    print("is_state_new_for: less than 500")
        #    return False #filter out
```
Never printed "out of order". Small glitches noticed (as in video).
When second was uncommented, often printed "less than 500". Small to average glitches noticed.

**Comment by ursoft** [comment] 2022-02-28 14:53
Also tried to switch filter off - nothing changed. Next test: the same route and hardware environment + retail server.

**Comment by oldnapalm** [comment] 2022-02-28 15:15
> Also tried to switch filter off - nothing changed.

Yes, I believe the filter (check if state was already sent) is useful only when a player has high latency.

**Closed as completed** 2022-04-21 18:07 UTC
